#!/usr/bin/env bash
# grkr container entrypoint — prepares workspace + config, then runs supervisor or CLI.
# Design goals: zero-boilerplate docker/helm; secrets via env; persistent /workspace.
set -euo pipefail

GRKR_HOME="${GRKR_HOME:-/opt/grkr}"
GRKR_GLEAM_PROJECT_ROOT="${GRKR_GLEAM_PROJECT_ROOT:-$GRKR_HOME}"
export GRKR_GLEAM_PROJECT_ROOT

WORKSPACE="${WORKSPACE_DIR:-${GRKR_ROOT:-/workspace}}"
export GRKR_ROOT="$WORKSPACE"
export GRKR_CONFIG_FILE="${GRKR_CONFIG_FILE:-$WORKSPACE/.grkr/config.sh}"
export PATH="$GRKR_HOME/bin:${PATH}"

log() { printf 'grkr-entry: %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

# --- helpers -----------------------------------------------------------------

resolve_repo_slug() {
  # Prefer explicit REPO; accept GRKR_REPO; fall back to empty.
  local raw="${REPO:-${GRKR_REPO:-}}"
  raw="${raw#https://github.com/}"
  raw="${raw#http://github.com/}"
  raw="${raw#git@github.com:}"
  raw="${raw%.git}"
  printf '%s' "$raw"
}

ensure_workspace_layout() {
  mkdir -p "$WORKSPACE"
  cd "$WORKSPACE"

  # Supervisor looks up workers under $GRKR_ROOT/bin/* and bin/grkr.
  # Overlay tool install into the workspace without clobbering a real project bin/.
  if [ ! -e "$WORKSPACE/bin/grkr" ]; then
    log "linking grkr bin/ into workspace"
    mkdir -p "$WORKSPACE/bin"
    # Prefer full tree link when workspace has no bin yet
    if [ -z "$(ls -A "$WORKSPACE/bin" 2>/dev/null || true)" ]; then
      rm -rf "$WORKSPACE/bin"
      ln -sfn "$GRKR_HOME/bin" "$WORKSPACE/bin"
    else
      for f in "$GRKR_HOME"/bin/*; do
        base=$(basename "$f")
        [ -e "$WORKSPACE/bin/$base" ] || ln -sfn "$f" "$WORKSPACE/bin/$base"
      done
    fi
  fi

  mkdir -p "$WORKSPACE/.grkr"/{tasks,state,locks,worktrees,logs,archive}

  # Persist gleam project root for any child that sources config only
  if [ -n "${GRKR_GLEAM_PROJECT_ROOT:-}" ]; then
    export GRKR_GLEAM_PROJECT_ROOT
  fi
}

clone_or_update_repo() {
  local slug repo_url token
  slug=$(resolve_repo_slug)
  [ -n "$slug" ] || die "REPO or GRKR_REPO is required (owner/name)"

  token="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
  if [ -n "${TARGET_REPO_URL:-}" ]; then
    repo_url="$TARGET_REPO_URL"
  elif [ -n "$token" ]; then
    repo_url="https://x-access-token:${token}@github.com/${slug}.git"
  else
    repo_url="https://github.com/${slug}.git"
  fi

  if [ -d "$WORKSPACE/.git" ]; then
    log "workspace already a git repo; ensuring origin remote"
    if ! git -C "$WORKSPACE" remote get-url origin >/dev/null 2>&1; then
      git -C "$WORKSPACE" remote add origin "$repo_url"
    else
      # Keep a tokenized push URL when token present (in-memory only for this process tree)
      if [ -n "$token" ]; then
        git -C "$WORKSPACE" remote set-url origin "$repo_url" || true
      fi
    fi
    return 0
  fi

  # Empty volume → clone into workspace
  if [ -z "$(ls -A "$WORKSPACE" 2>/dev/null | grep -v '^\.grkr$' || true)" ]; then
    log "cloning $slug into $WORKSPACE"
    # clone into temp then move to keep volume mount root
    local tmp
    tmp=$(mktemp -d)
    git clone --depth=1 --branch "${MAIN_BRANCH:-main}" "$repo_url" "$tmp/repo" \
      || git clone "$repo_url" "$tmp/repo"
    # Move contents including dotfiles
    shopt -s dotglob nullglob
    mv "$tmp/repo"/* "$WORKSPACE"/
    shopt -u dotglob nullglob
    rm -rf "$tmp"
  else
    die "WORKSPACE $WORKSPACE is non-empty and not a git repo. Mount an empty volume or a clone of $slug."
  fi
}

configure_git_identity() {
  git config --global user.name "${BOT_GIT_NAME:-grkr-bot}"
  git config --global user.email "${BOT_GIT_EMAIL:-grkr-bot@users.noreply.github.com}"
  git config --global --add safe.directory "$WORKSPACE" || true
  # Prefer merge-less pulls for robot
  git config --global pull.rebase true || true
}

configure_gh_auth() {
  local token="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
  if [ -z "$token" ]; then
    log "warning: GH_TOKEN/GITHUB_TOKEN unset — doctor/gh calls will fail until provided"
    return 0
  fi
  export GH_TOKEN="$token"
  export GITHUB_TOKEN="$token"
  # Non-interactive auth for gh
  printf '%s\n' "$token" | gh auth login --with-token >/dev/null 2>&1 || true
  gh auth setup-git >/dev/null 2>&1 || true
}

write_config_if_needed() {
  local slug owner number path force
  path="$GRKR_CONFIG_FILE"
  force="${GRKR_FORCE_CONFIG:-0}"
  slug=$(resolve_repo_slug)
  owner="${PROJECT_OWNER:-${slug%%/*}}"
  number="${PROJECT_NUMBER:-}"

  if [ -f "$path" ] && [ "$force" != "1" ] && [ "$force" != "true" ]; then
    log "using existing config: $path"
    return 0
  fi

  [ -n "$number" ] || die "PROJECT_NUMBER is required to generate $path (or mount a config file)"

  mkdir -p "$(dirname "$path")"
  log "writing $path for $slug project=$number"
  cat >"$path" <<EOF
# Generated by grkr container entrypoint — override via env or mount.
REPO="${slug}"
MAIN_BRANCH="${MAIN_BRANCH:-main}"
PROJECT_OWNER="${owner}"
PROJECT_NUMBER="${number}"
STATUS_FIELD_NAME="${STATUS_FIELD_NAME:-Status}"
TODO_VALUE="${TODO_VALUE:-Todo}"
IN_PROGRESS_VALUE="${IN_PROGRESS_VALUE:-In Progress}"
DONE_VALUE="${DONE_VALUE:-Done}"
BACKLOG_VALUE="${BACKLOG_VALUE:-Backlog}"
PRIORITY_FIELD_NAME="${PRIORITY_FIELD_NAME:-Priority}"
PRIORITY_MODE="${PRIORITY_MODE:-single_select}"
PRIORITY_ORDER="${PRIORITY_ORDER:-P0,P1,P2,P3}"
LOOP_INTERVAL_SECS="${LOOP_INTERVAL_SECS:-20}"
COMMENT_PREFIX="${COMMENT_PREFIX:-@:robot:}"
MAX_PARALLEL_COMMENT_JOBS="${MAX_PARALLEL_COMMENT_JOBS:-4}"
MAX_PARALLEL_PR_JOBS="${MAX_PARALLEL_PR_JOBS:-2}"
ISSUE_EXECUTION_CONCURRENCY="${ISSUE_EXECUTION_CONCURRENCY:-1}"
CONFLICT_STRATEGY="${CONFLICT_STRATEGY:-rebase}"
TEST_COMMAND="${TEST_COMMAND:-npm test}"
BUILD_COMMAND="${BUILD_COMMAND:-}"
BOT_GIT_NAME="${BOT_GIT_NAME:-grkr-bot}"
BOT_GIT_EMAIL="${BOT_GIT_EMAIL:-grkr-bot@users.noreply.github.com}"
BOT_LOGIN="${BOT_LOGIN:-}"
CODEX_MODEL="${CODEX_MODEL:-}"
CODEX_ARGS="${CODEX_ARGS:-}"
ENABLE_AUTO_PUSH="${ENABLE_AUTO_PUSH:-true}"
ENABLE_PROJECT_STATUS_UPDATES="${ENABLE_PROJECT_STATUS_UPDATES:-true}"
ENABLE_PR_COMMENTS="${ENABLE_PR_COMMENTS:-true}"
ENABLE_ISSUE_COMMENTS="${ENABLE_ISSUE_COMMENTS:-true}"
KEEP_FAILED_WORKTREES="${KEEP_FAILED_WORKTREES:-false}"
ALLOW_ISSUE_REFUSAL="${ALLOW_ISSUE_REFUSAL:-true}"
REFUSAL_REQUIRES_BACKLOG_MOVE="${REFUSAL_REQUIRES_BACKLOG_MOVE:-true}"
EOF
}

install_coding_agent_shims() {
  # Optional: host-mounted CLIs at /opt/coding-agents/{codex,grok}
  if [ -x /opt/coding-agents/codex ] && [ ! -x "$(command -v codex 2>/dev/null || true)" ]; then
    mkdir -p "$HOME/.local/bin"
    ln -sfn /opt/coding-agents/codex "$HOME/.local/bin/codex"
    export PATH="$HOME/.local/bin:$PATH"
  fi
  if [ -x /opt/coding-agents/grok ]; then
    mkdir -p "$HOME/.grok/bin" "$HOME/.local/bin"
    ln -sfn /opt/coding-agents/grok "$HOME/.grok/bin/grok"
    ln -sfn /opt/coding-agents/grok "$HOME/.local/bin/grok"
    export PATH="$HOME/.local/bin:$PATH"
    export GROK_BIN="${GROK_BIN:-$HOME/.grok/bin/grok}"
  fi
  # Prefer GRKR_CODING_AGENT from env (default leave unset → product default)
  if [ -n "${GRKR_CODING_AGENT:-}" ]; then
    export GRKR_CODING_AGENT
  fi
}

prepare_linear_creds() {
  mkdir -p "$HOME/.linear"
  if [ -n "${GRKR_LINEAR_ACCESS_TOKEN:-}" ]; then
    printf '%s\n' "$GRKR_LINEAR_ACCESS_TOKEN" >"$HOME/.linear/token.txt"
    chmod 600 "$HOME/.linear/token.txt"
  fi
  if [ -n "${LINEAR_CLIENT_ID:-}" ] && [ -n "${LINEAR_CLIENT_SECRET:-}" ]; then
    cat >"$HOME/.linear/secret.txt" <<EOF
client_id=${LINEAR_CLIENT_ID}
client_secret=${LINEAR_CLIENT_SECRET}
EOF
    chmod 600 "$HOME/.linear/secret.txt"
  fi
}

bootstrap() {
  configure_git_identity
  configure_gh_auth
  install_coding_agent_shims
  prepare_linear_creds
  clone_or_update_repo
  ensure_workspace_layout
  write_config_if_needed
  cd "$WORKSPACE"
  export REPO PROJECT_OWNER PROJECT_NUMBER MAIN_BRANCH LOOP_INTERVAL_SECS
  REPO="$(resolve_repo_slug)"
  export REPO
}

usage() {
  cat <<'EOF'
grkr container entrypoint

Usage:
  docker run ... grkr                 # alias for supervisor
  docker run ... supervisor           # long-lived robot-main loop (default)
  docker run ... doctor               # startup validation only
  docker run ... init <project-id>    # write .grkr/config.sh then exit
  docker run ... issue <n>            # grkr --issue N
  docker run ... linear-issue <id>    # grkr --linear-issue ID
  docker run ... shell                # interactive bash in workspace
  docker run ... -- <cmd> [args...]   # raw command

Required env:
  REPO or GRKR_REPO          owner/name
  PROJECT_NUMBER             GitHub Project number
  GH_TOKEN or GITHUB_TOKEN   GitHub auth

Optional env:
  PROJECT_OWNER, MAIN_BRANCH, LOOP_INTERVAL_SECS, BOT_LOGIN,
  GRKR_CODING_AGENT=codex|grok, XAI_API_KEY, GRKR_LINEAR_ACCESS_TOKEN,
  TARGET_REPO_URL, WORKSPACE_DIR, GRKR_FORCE_CONFIG=1
EOF
}

# --- main --------------------------------------------------------------------

cmd="${1:-supervisor}"
if [ "$#" -gt 0 ]; then
  shift
fi

case "$cmd" in
  -h|--help|help)
    usage
    exit 0
    ;;
  shell|bash)
    bootstrap
    exec bash "$@"
    ;;
  doctor)
    bootstrap
    exec "$GRKR_HOME/bin/doctor.sh"
    ;;
  init)
    bootstrap
    # Prefer generated config already written; still allow grkr init if requested
    if [ -n "${1:-}" ] && [ ! -f "$GRKR_CONFIG_FILE" ]; then
      exec "$GRKR_HOME/bin/grkr" init "$1"
    fi
    log "config ready at $GRKR_CONFIG_FILE"
    exit 0
    ;;
  issue|--issue)
    bootstrap
    [ -n "${1:-}" ] || die "issue number required"
    exec "$GRKR_HOME/bin/grkr" --issue "$1"
    ;;
  linear-issue|--linear-issue)
    bootstrap
    [ -n "${1:-}" ] || die "linear issue id required"
    exec "$GRKR_HOME/bin/grkr" --linear-issue "$1"
    ;;
  supervisor|robot|robot-main|grkr)
    bootstrap
    log "starting supervisor (robot-main) in $WORKSPACE"
    exec "$GRKR_HOME/bin/robot-main.sh" "$@"
    ;;
  --)
    bootstrap
    exec "$@"
    ;;
  *)
    # Unknown first arg → treat as raw command after light bootstrap when workspace ready
    if [ -d "$WORKSPACE/.git" ] || [ -n "${REPO:-${GRKR_REPO:-}}" ]; then
      bootstrap
    fi
    exec "$cmd" "$@"
    ;;
esac
